config/routes.rb
FrienderyV10::Application.routes.draw do
  get "welcome/index"
  resources :events
  root to: "welcome#index"
end

app/models/event.rb
class Event < ActiveRecord::Base
	validates :name, presence: true, length: { minimum: 4 }
	validates :description, presence: true, length: { minimum: 15 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def new
		@event = Event.new
	end
	
	def create
		@event = Event.new(params[:event].permit(:name, :numberofpeople, :when, :where, :description))
		if @event.save
			redirect_to @event
		else
			render 'new'
		end
	end
	
	def show
		@event = Event.find(params[:id])
	end
	
	def index
		@events = Event.all
	end
	
	def edit
		@event = Event.find(params[:id])
	end
	
	def update
		@event = Event.find(params[:id])
		if @event.update(params[:event].permit(:name, :numberofpeople, :when, :where, :description))
			redirect_to @event
		else
			render 'edit'
		end
	end
	
	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to events_path
	end

	private
		def event_params
			params.require(:event).permit(:name, :numberofpeople, :when, :where, :description)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
	<% if @event.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
    <ul>
		<% @event.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
    </ul>
	</div>
	<% end %>
	<p>
		<f.label for="event_name">EventName</label>
		<%= f.text_field(:name) %>
		<f.label for="event_numberofpeople">Number of People</label>
		<%= f.text_field(:numberofpeople) %>
	</p>
	
	<p>
		<f.label for="event_hen">When</label>
		<%= f.text_field(:when) %>
		<f.label for="event_where">Where</label>
		<%= f.text_field(:where) %>
	</p>
	
	<p>
		<f.label for="event_description">Description</label><br>
		<%= f.text_area(:description, size: "80x10")%>
	</p>
 
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Events</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Events List</h1>
<%= link_to 'New Event', new_event_path %>
<table>
	<tr>
		<th>EventName</th>
		<th>#OfPeople</th>
		<th>When</th>
		<th>Where</th>
		<th>Description</th>
	</tr>
 
  <% @events.each do |event| %>
    <tr>
		<td><%= event.name %></td>
		<td><%= event.numberofpeople %></td>
		<td><%= event.when %></td>
		<td><%= event.where %></td>
		<td><%= event.description %></td>
		<td><%= link_to 'Show', event %></td>
		<td><%= link_to 'Edit', edit_event_path(event) %></td>
		<td><%= link_to 'Destroy', event_path(event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/events/new.html.erb
<h1>CREATE</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p>
	<strong>Event Name:</strong>
	<%= @event.name %>
	<strong>Number Of People:</strong>
	<%= @event.numberofpeople %>
</p>

<p>
	<strong>When:</strong>
	<%= @event.when %>
	<strong>Where:</strong>
	<%= @event.where %>
</p>

<p>
	<strong>Description:</strong><br>
	<%= @event.description %>
</p>

<%= link_to 'Back', events_path %>|<%= link_to 'Edit', edit_event_path(@event) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FrienderyV10</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to FRIENDERY! Building....</h1>
<%= link_to "My Events", controller: "events" %>